In [1]:
import pandas as pd
import glob
import re
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
import datetime

In [2]:
import pickle

### Random Forest Classifier

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [4]:
# #Reading Dataset
# path = "/content/drive/MyDrive/Colab Notebooks/Dataset_clean.csv"
# dataset = pd.read_csv(path)

In [5]:
# newdf = pd.DataFrame()

# #oversampling
# category = dataset['Label'].unique()

# for i in category:
#     tmp = dataset[dataset['Label'] == i]
#     val = tmp.shape[0]
    
#     tmp = tmp.sample(171509,replace=True)
#     newdf = pd.concat([newdf,tmp],axis=0)
    

In [ ]:
# dataset.shape,newdf.shape

In [6]:
#pickle load
X_file = open('feature_data', 'rb')
X = pickle.load(X_file)   
X_file.close()

y_file = open('label_data', 'rb')
y = pickle.load(y_file)   
y_file.close()

In [7]:
clf = RandomForestClassifier(max_depth=2, random_state=0)

In [8]:
# data = np.c_[X, y]

In [9]:
# data.shape

In [10]:
# data = data[~np.isnan(data).any(axis=1), :]

In [11]:
# data.astype('float64')

In [12]:
# data.shape

In [13]:
# X = data[:,:-1]
# y = data[:,-1]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2058108, 78), (514527, 78), (2058108,), (514527,))

In [15]:
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

#### Accuracy: RF

In [16]:
y_pred = clf.predict(X_test)

In [17]:
accuracy_score(y_test, y_pred)

0.6312924297461552

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

/home/shailesh/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00     34333
           1       0.39      0.96      0.55     34024
           2       0.96      0.13      0.23     34271
           3       0.00      0.00      0.00     34378
           4       0.43      0.90      0.58     34344
           5       0.55      0.84      0.66     34151
           6       0.95      0.62      0.75     34343
           7       0.95      1.00      0.97     34216
           8       1.00      1.00      1.00     34559
           9       0.89      0.70      0.78     34339
          10       0.68      0.48      0.56     34168
          11       0.76      0.96      0.85     34489
          12       0.00      0.00      0.00     34539
          13       0.69      0.95      0.80     34119
          14       0.49      0.93      0.64     34254

    accuracy                           0.63    514527
   macro avg       0.58      0.63      0.56    514527
weighted avg       0.58   

/home/shailesh/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/shailesh/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [19]:
unique, counts = np.unique(y_pred, return_counts = True)
unique, counts

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14]),
 array([84568,  4619,     8, 72813, 52226, 22413, 36152, 34559, 26748,
        24399, 43835, 46809, 65378]))

In [20]:
unique, counts = np.unique(y_test, return_counts = True)
unique, counts

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([34333, 34024, 34271, 34378, 34344, 34151, 34343, 34216, 34559,
        34339, 34168, 34489, 34539, 34119, 34254]))

In [21]:
import joblib

In [22]:
joblib.dump(clf, 'IDS_model_RF.joblib')

['IDS_model_RF.joblib']

In [23]:
clf_preds = clf.predict(X_test)

In [24]:
clf_preds.shape

(514527,)

In [25]:
clf_preds[:20]

array([ 8,  4, 14,  4, 14,  4,  5, 14,  1, 13, 10,  4, 14,  5,  8, 13, 11,
        4, 13,  1])

In [26]:
clf.get_params

<bound method BaseEstimator.get_params of RandomForestClassifier(max_depth=2, random_state=0)>

#### Plotting loss and accuracy graphs

In [27]:
from sklearn.tree import plot_tree

In [ ]:
fig = plt.figure(figsize=(15, 10))
plot_tree(clf.estimators_[0], 
          feature_names=wine.feature_names,
          class_names=wine.target_names, 
          filled=True, impurity=True, 
          rounded=True)